### ISSUE TITLE
Opt in to flux-backbone

### ISSUE THREAD

**Issue by megawac** [vidoss/flux-backbone#2]
There is a lot of code (think plugins, third party apps, second party apps, legacy) that may be outside of the authors control. I suggest you add a view that is opt out rather than enforcing an immutable style throughout a codebase.

One way to accomplish this would be instead of overriding View, adding a `FluxView` which tracks immutability (would make tracking more challenging).

**Comment by vidoss** [comment]
It doesn't affect existing Backbone collections and models. Only when you new FluxBackbone.Model or FluxBackbone.Collection you will get this functionality. So libraries using backbone model and collection should just work as is.
